swagger: "2.0"
info:
  version: "0.0.1"
  title: Mobile Payments API
# during dev, should point to your local machine
host: localhost:6001
# basePath prefixes all resource paths 
basePath: /v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /remitter:
    # binds a127 app logic to a route
    x-swagger-router-controller: remitter
    get:
      description: Get a remitter by mobile phone number
      # used as the method name of the controller
      operationId: getRemitter
      parameters:
        - name: mobileNumber
          in: query
          description: The mobile phone number of the remitter
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Remitter"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
#    get:
#      description: Get all remitters
      # used as the method name of the controller
#      operationId: getAllRemitters
#      responses:
#        "200":
#          description: Success
#          type: array
#          items:
            # a pointer to a definition
#            $ref: "#/definitions/Remitter"
        # responses may fall through to errors
#        default:
#          description: Error
#          schema:
#            $ref: "#/definitions/ErrorResponse"
    post:
      description: Register a new remitter mobile number
      operationId: addRemitter
      parameters:
        - name: remitter
          in: body
          description: Remitter object to store
          required: true
          schema:
            $ref: "#/definitions/Remitter"
            required:
              - name
              - identifier
              - acount
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Remitter"
        "201":
          description: Success
          schema:
            $ref: "#/definitions/Remitter" 
        "405":
          description: Invalid input
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Update a remitter
      operationId: updateRemitter
      parameters:
        - name: mobileNumber
          in: query
          description: Key to remitter to be updated
          required: true
          type: string
        - name: remitter
          in: body
          description: New remitter properties. mobileNumber is the key so it will not be changed
          required: true
          schema:
            $ref: "#/definitions/Remitter"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Remitter"
        "201":
          description: Success
          schema:
            $ref: "#/definitions/Remitter" 
        "405":
          description: Invalid input
        "404":
          description: Not found
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Delete a remitter
      operationId: deleteRemitter
      parameters:
        - name: mobileNumber
          in: query
          description: Key to remitter to be deleted
          required: true
          type: string
      responses:
        "200":
          description: Success
        "201":
          description: Success
        "404":
          description: Not found
          schema:
            $ref: "#/definitions/ErrorResponse"
    
# complex objects have schema definitions
definitions:
  Remitter:
    properties:
      remitterName:
        type: string
      mobileNumber:
        type: string
      account:
        $ref: "#/definitions/Account"
  Merchant:
    properties:
      name:
        type: string
      abn:
        type: string
      account:
        $ref: "#/definitions/Account"
  Invoice:
    properties:
      invoice:
        type: string
      amount:
        type: number
      status:
        type: string
        enum:
          - presented
          - initiated
          - successful
          - failed
      remitterMobile:
        type: string
      merchantABN:
        type: string
      created:
        type: string
  Account:
    properties:
      name:
        type: string
      bsb:
        type: string
      account:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
